package client_test

import (
	"regexp"
	"sync"
	"testing"

	"github.com/isucon10-qualify/isucon10-qualify/bench/client"
)

var botUserAgentRegExpList []*regexp.Regexp = []*regexp.Regexp{
	regexp.MustCompile(`ISUCONbot(-Mobile)?`),
	regexp.MustCompile(`ISUCONbot-Image\/`),
	regexp.MustCompile(`Mediapartners-ISUCON`),
	regexp.MustCompile(`ISUCONCoffee`),
	regexp.MustCompile(`ISUCONFeedSeeker(Beta)?`),
	regexp.MustCompile(`crawler \(https:\/\/isucon\.invalid\/(support\/faq\/|help\/jp\/)`),
	regexp.MustCompile(`isubot`),
	regexp.MustCompile(`Isupider`),
	regexp.MustCompile(`Isupider(-image)?\+`),
	regexp.MustCompile(`(?i)(bot|crawler|spider)(?:[-_ .\/;@()]|$)`),
}

func isBotUserAgent(ua string) bool {
	for _, botUserAgentRegExp := range botUserAgentRegExpList {
		if botUserAgentRegExp.MatchString(ua) {
			return true
		}
	}
	return false
}

func Test_UserAgent(t *testing.T) {
	var wg sync.WaitGroup
	for i := 0; i < 10000; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			ua := client.GenerateUserAgent()
			if isBotUserAgent(ua) {
				t.Errorf("Bot User Agent was generated by GenerateUserAgent func: %v", ua)
			}
		}()
	}

	wg.Wait()
}

func Test_BotUserAgent(t *testing.T) {
	var wg sync.WaitGroup
	for i := 0; i < 10000; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			ua := client.GenerateBotUserAgent()
			if !isBotUserAgent(ua) {
				t.Errorf("User Agent was generated by GenerateBotUserAgent func: %v", ua)
			}
		}()
	}

	wg.Wait()
}
